language: rust

matrix:
  include:
    - name: "Build & test on nightly WITH nightly feature"
      rust: nightly
      script:
        - cargo build --verbose --features=nightly || travis_terminate 1
        - cargo test --verbose --features=nightly || travis_terminate 1
    - name: "Build & test on nightly WITHOUT nightly feature"
      rust: nightly
      script:
        - cargo build --verbose || travis_terminate 1
        - cargo test --verbose || travis_terminate 1
    - name: "Build on beta"
      rust: beta
      script:
        - cargo build --verbose
        - cargo build --verbose --examples

env:
  global:
    - RUSTFLAGS="--deny warnings"
